# Generated by Django 3.2.17 on 2023-02-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
