# Generated by Django 3.2.18 on 2023-02-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
