# Generated by Django 3.2.18 on 2023-02-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': ' message'},
        ),
    ]
