# Generated by Django 3.2.17 on 2023-02-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230212_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_data',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
